export const cardArray = [
	{
		id: 0,
		title: 'Пвх материал 1-й сорт',
		price: '170 ₽',
		address: 'Казань, р-н Вахатовский',
		date: '10 июля 11:39',
		img: 'https://placehold.jp/266x266.png',
	},
	{
		id: 1,
		title: 'Пвх материал 2-й сорт',
		price: '100 ₽',
		address: 'Казань, р-н Вахатовский',
		date: '10 июля 11:39',
		img: 'https://placehold.jp/266x266.png',
	},
  {
		id: 2,
		title: 'Пвх материал 3-й сорт',
		price: '200 ₽',
		address: 'Казань, р-н Вахатовский',
		date: '10 июля 11:39',
		img: 'https://placehold.jp/266x266.png',
	},
	{
		id: 3,
		title: 'Пвх материал 4-й сорт',
		price: '400 ₽',
		address: 'Казань, р-н Вахатовский',
		date: '10 июля 11:39',
		img: 'https://placehold.jp/266x266.png',
	},
  {
		id: 4,
		title: 'Пвх материал 5-й сорт',
		price: '1600 ₽',
		address: 'Казань, р-н Вахатовский',
		date: '10 июля 11:39',
		img: 'https://placehold.jp/266x266.png',
	},
	{
		id: 5,
		title: 'Пвх материал 6-й сорт',
		price: '2300 ₽',
		address: 'Казань, р-н Вахатовский',
		date: '10 июля 11:39',
		img: 'https://placehold.jp/266x266.png',
	},
];